export const departamentos = [
  "marketing",
  "vendas",
  "compras",
  "financeiro",
  "contabilidade",
  "recursos humanos",
  "tecnologia da informacao",
  "juridico",
  "logistica",
  "producao",
  "qualidade",
  "engenharia",
  "desenvolvimento de software",
  "atendimento ao cliente",
  "administrativo",
  "facilities infraestrutura",
  "seguranca da informacao",
  "pesquisa e desenvolvimento",
  "comunicacao interna",
  "operacoes",
  "planejamento estrategico",
  "projetos",
  "suprimentos",
  "almoxarifado",
  "transporte",
  "treinamento e desenvolvimento",
  "auditoria",
  "manutencao",
  "relacoes publicas",
  "comercial",
  "crm",
  "seguranca patrimonial",
  "governanca corporativa",
  "compliance",
  "atendimento pos venda",
  "expedicao",
  "sustentabilidade",
  "ecommerce",
  "desenvolvimento de produto",
  "controle de producao",
  "business intelligence",
  "atendimento juridico interno",
  "contas a pagar",
  "contas a receber",
  "infraestrutura de ti",
  "desenvolvimento",
  "suporte ao usuario",
  "engenharia de processos",
  "customer success",
  "ti"
];